In [1]:
# numpy is fast as they uses less bytes of memory, has contiguous memory(better vector processing, effective cache utilisation)
#lists uses more space in memory
import numpy as np

In [2]:
#initialize array
#1D
a = np.array([1,2,3])
print(a[1:])
#dimensions
a.ndim

#2D
b = np.array([[1,2,3],[3,4,5]])
print(b[0][1:])
b.ndim

#3D
c = np.array([[[1,2,3],[3,4,5]],[[2,4,5],[5,4,3]]])
c.ndim

[2 3]
[2 3]


3

In [3]:
#shape
b.shape

(2, 3)

In [7]:
#type
a.dtype = 'int16'
a.dtype

dtype('int16')

In [10]:
#size
c.itemsize

4

In [13]:
#total size
c.size
#c.nbytes = c.itemsize * c.size

12

### <h2>Accessing/changing specific elements, rows, columns ets </h2>

In [17]:
ar = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(ar)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [18]:
ar.shape

(2, 7)

In [19]:
ar.ndim

2

In [21]:
ar[0, 1:6:3]

array([2, 5])

# # # Initializing different types of array ###

In [28]:
#All Zeroes Matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
#All 1s Matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
#Any other number
np.full((2,3), 11)

array([[11, 11, 11],
       [11, 11, 11]])

In [37]:
#Any other number (full_like)
np.full(ar.shape, 100) 
np.full_like(ar, 99)

array([[99, 99, 99, 99, 99, 99, 99],
       [99, 99, 99, 99, 99, 99, 99]])

In [38]:
#Random Decimal Numbers
np.random.rand(4,3)

array([[0.57026475, 0.00725595, 0.20598552],
       [0.14788235, 0.23362117, 0.60498043],
       [0.16559413, 0.12384721, 0.38688694],
       [0.93801839, 0.40922675, 0.05322851]])

In [40]:
np.random.random_sample(ar.shape)

array([[0.55533171, 0.74730198, 0.7494323 , 0.15406986, 0.91570721,
        0.69046571, 0.74074913],
       [0.58389931, 0.03143048, 0.43827591, 0.06280501, 0.74912973,
        0.86301757, 0.67126444]])

In [52]:
#random integer value
np.random.randint(-2, 5, size = (3,3))

array([[ 2,  3,  2],
       [ 0, -1,  1],
       [-1,  2, -2]])

In [53]:
#identity square matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
#Repeat Matrix
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [79]:
#solution
output = np.ones((5,5))
output[1:4,1:4] = 0
output[2][2] = 9
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [84]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
b

array([100,   2,   3])